volumes:
  db-store:
  favicon:
    external: true

services:
  web:
    container_name: ${APP_NAME}-web-${ENV}
    build: 
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
      target: ${ENV}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
      - favicon:/var/www/src/public/favicon
      - ./infra/docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro

  app:
    container_name: ${APP_NAME}-app-${ENV}
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - USER_NAME=${USER_NAME}
      target: ${ENV}
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
      - favicon:/var/www/src/public/favicon

  db:
    container_name: ${APP_NAME}-db-${ENV}
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  db-testing:
    container_name: ${APP_NAME}-db-testing-${ENV}
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - 3000:3306
    environment:
      - MYSQL_DATABASE=${DB_TEST_NAME}
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"