volumes:
  db-store:
  storage:
  public:
  favicon:
    external: true

networks:
  internal:
  webnet:
    external: true

services:
  app:
    image: ${DOCKER_USERNAME}/${APP_NAME}-app-${ENV}:${VERSION}
    container_name: ${APP_NAME}-app-${ENV}
    user: "${UID}:${GID}"
    volumes:
      - ./src/.env:/var/www/src/.env
      - storage:/var/www/src/storage/app/public
      - public:/var/www/src/public
      - favicon:/var/www/src/public/favicon
    networks:
      - internal

  web:
    image: ${DOCKER_USERNAME}/${APP_NAME}-web-${ENV}:${VERSION}
    container_name: ${APP_NAME}-web-${ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webnet"
      - "traefik.http.routers.staging-web.entrypoints=websecure"
      - "traefik.http.routers.staging-web.rule=Host(`staging.cfcrating.com`)"
      - "traefik.http.routers.staging-web.tls=true"
      - "traefik.http.routers.staging-web.tls.certresolver=myresolver"
      - "traefik.http.services.staging-web.loadbalancer.server.port=80"
    volumes:
      - storage:/var/www/src/storage/app/public
      - public:/var/www/src/public
      - favicon:/var/www/src/public/favicon
    expose:
      - "80"
    networks:
      - webnet
      - internal
    depends_on:
      - app
    restart: always

  db:
    image: ${DOCKER_USERNAME}/${APP_NAME}-db-${ENV}:${VERSION}
    container_name: ${APP_NAME}-db-${ENV}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    networks:
      - internal

  scheduler:
    image: ${DOCKER_USERNAME}/${APP_NAME}-app-${ENV}:${VERSION}
    container_name: ${APP_NAME}-scheduler-${ENV}
    user: "${UID}:${GID}"
    command: sh -c "while true; do php /var/www/src/artisan schedule:run; sleep 60; done"
    volumes:
      - ./src/.env:/var/www/src/.env
    networks:
      - internal

  queue:
    image: ${DOCKER_USERNAME}/${APP_NAME}-app-${ENV}:${VERSION}
    container_name: ${APP_NAME}-queue-${ENV}
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - ./src/.env:/var/www/src/.env
      - storage:/var/www/src/storage/app/public
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - internal
