services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "${WEB_PORT}:80"
      - "${SSL_PORT}:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    environment:
      - DEFAULT_EMAIL=${EMAIL}
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
   
volumes:
  certs:
  html:
  acme:
