name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "local"
        type: choice
        options:
          - local
          - test
          - production
      deploy_message:
        description: "Deployment message"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            src/
          sparse-checkout-cone-mode: false

      - name: Deploy app
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: src/
          remote_path: src/cfcrating/src/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}