name: Deploy All Files

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "production"
        type: choice
        options:
          - local
          - test
          - production
      deploy_message:
        description: "Deployment message"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy All Files
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude-from=.github/workflows/.actionignore
          path: .
          remote_path: /home/${{ secrets.SSH_USER }}/src/cfcrating/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}