name: Deploy Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      app_changed: ${{ steps.changes.outputs.app }}
      web_changed: ${{ steps.changes.outputs.web }}
      db_changed: ${{ steps.changes.outputs.db }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'infra/docker/php/**'
              - 'src/**'
            web:
              - 'infra/docker/nginx/**'
            db:
              - 'infra/docker/mysql/**'
  
  call_build_push_app:
    if: needs.detect_changes.outputs.app_changed == 'true'
    needs: detect_changes
    uses: ./.github/workflows/build-push-app.yml
    secrets: inherit
  
  call_build_push_web:
    if: needs.detect_changes.outputs.web_changed == 'true'
    needs: detect_changes
    uses: ./.github/workflows/build-push-web.yml
    secrets: inherit

  call_build_push_db:
    if: needs.detect_changes.outputs.db_changed == 'true'
    needs: detect_changes
    uses: ./.github/workflows/build-push-db.yml
    secrets: inherit

  call_rsync:
    needs: detect_changes
    uses: ./.github/workflows/rsync.yml
    secrets: inherit
  
  deploy:
    if: always()
    needs: [call_build_push_app, call_build_push_web, call_build_push_db, call_rsync]
    uses: ./.github/workflows/pull-and-launch.yml
    secrets: inherit
    