name: Deploy Infrastructure (Docker)

on:
  push:
    # paths:
    #   - "infra/docker/nginx/**"
    #   - "infra/docker/php/**"
    #   - "infra/docker/mysql/**"
    #   - "docker-compose.yml"
    #   - ".github/workflows/infra.yml"
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "local"
        type: choice
        options:
          - local
          - test
          - production
      deploy_message:
        description: "Deployment message"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            infra/
          sparse-checkout-cone-mode: false

      - name: Determine Changed Services
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1)

          DEPLOY_NGINX=false
          DEPLOY_PHP=false
          DEPLOY_MYSQL=false
          DEPLOY_DOCKER_YML=false
          DEPLOY_MAKEFILE=false

          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" =~ ^infra/docker/nginx/ ]]; then
              DEPLOY_NGINX=true
            elif [[ "$FILE" =~ ^infra/docker/php/ ]]; then
              DEPLOY_PHP=true
            elif [[ "$FILE" =~ ^infra/docker/mysql/ ]]; then
              DEPLOY_MYSQL=true
            elif [[ "$FILE" == "docker-compose.yml" ]]; then
              DEPLOY_DOCKER_YML=true
            elif [[ "$FILE" = "Makefile" ]]; then
              DEPLOY_MAKEFILE=true
            fi
          done

          echo "DEPLOY_NGINX=$DEPLOY_NGINX" >> $GITHUB_ENV
          echo "DEPLOY_PHP=$DEPLOY_PHP" >> $GITHUB_ENV
          echo "DEPLOY_MYSQL=$DEPLOY_MYSQL" >> $GITHUB_ENV
          echo "DEPLOY_DOCKER_YML=$DEPLOY_DOCKER_YML" >> $GITHUB_ENV
          echo "DEPLOY_MAKEFILE=$DEPLOY_MAKEFILE" >> $GITHUB_ENV

      - name: Deploy Nginx
        if: env.DEPLOY_NGINX == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/nginx
          remote_path: src/cfcrating/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy PHP
        if: env.DEPLOY_PHP == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/php
          remote_path: src/cfcrating/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy MySQL
        if: env.DEPLOY_MYSQL == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/mysql
          remote_path: src/cfcrating/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy docker compose yml
        if: env.DEPLOY_DOCKER_YML == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: docker-compose.yml
          remote_path: src/cfcrating/docker-compose.yml
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Makefile
        if: env.DEPLOY_MAKEFILE == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: Makefile
          remote_path: src/cfcrating/Makefile
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}