name: Make Env

on:
  workflow_dispatch:

jobs:
  make-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SSH_USER }}/src/cfcrating/src
          
            cd /home/${{ secrets.SSH_USER }}/src/cfcrating

            echo "${{ secrets.ENV }}" | base64 --decode > .env
            echo "${{ secrets.ENV_SRC }}" | base64 --decode > ./src/.env

            make key
            make clear
            make cache