name: make env file

on:
  workflow_dispatch:

jobs:
  make-env:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ vars.VERSION }}
    steps:
      - name: make .env and src/.env
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV }}" | base64 --decode > /opt/production/.env
            echo "${{ secrets.ENV_SRC }}" | base64 --decode > /opt/production/src/.env

            export VERSION="${{ env.VERSION }}"
            echo -e "\nVERSION=${{ env.VERSION }}" >> /opt/production/.env