name: Build and Push web container [Staging]

on:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH_WEB: infra/docker/nginx/Dockerfile
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      VERSION: ${{ vars.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode .env from GitHub Secrets and set environment variables
        run: |
          echo "${{ secrets.ENV_STAGING }}" | base64 --decode > .env

          while IFS='=' read -r key value; do
            if [[ ! -z "$key" && ! "$key" =~ ^# ]]; then
              echo "::add-mask::$value"
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH_WEB }}
          target: ${{ env.ENV }}
          build-args: |
            GID=${{ env.GID }}
            UID=${{ env.UID }}
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/cfcrating-web-${{ env.ENV }}:${{ env.VERSION }}